### ISSUE TITLE
Fog appears on some maps

### ISSUE THREAD

**Issue by Nord1cWarr1or** [ollerjoaco/MH_TrinityRender#5]
Fog appears on some maps, where it does not exist without using Trinity.

I think it has to do with water and misidentifying its coordinates (?)
because:
1. it looks like a fog under water
2. it happens on maps with water
3. `gl_fog 0` not works
4. on the map [de_dust2_2020](https://gamebanana.com/mods/83688) there is a small water - a fountain. So, the fog appears if you walk up to it and do not even touch the water itself.

![20230430142026_1](https://user-images.githubusercontent.com/47604048/236506566-1e7c0505-5183-48f4-ac13-1f7357e1c3d3.jpg)
![20230430142034_1](https://user-images.githubusercontent.com/47604048/236506573-d817214c-6aa7-4715-8d6e-bd8ee9236ee9.jpg)

![20230430142028_1](https://user-images.githubusercontent.com/47604048/236506607-860d9441-8be7-4305-b5c0-e6f936beb41f.jpg)

Other examples:
With Trinity:

![20230505152553_1](https://user-images.githubusercontent.com/47604048/236504212-4cd25e29-d279-49a1-8a2c-c2315458efd4.jpg)

Without it:

![20230505152442_1](https://user-images.githubusercontent.com/47604048/236504111-572fc45f-0a3e-4c04-bfe7-2171a34f30ff.jpg)

![20230505154234_1](https://user-images.githubusercontent.com/47604048/236505910-d9a17048-1320-4524-be3b-87d908e07d04.jpg)

![20230505154551_1](https://user-images.githubusercontent.com/47604048/236505948-d77287b0-ffc5-4aa4-9665-81b19c86de70.jpg)

![20230505155603_1](https://user-images.githubusercontent.com/47604048/236507801-2d94391b-4fa4-4f78-a1b0-92bcd667aa02.jpg)

![20230505155633_1](https://user-images.githubusercontent.com/47604048/236507830-1537021a-484f-443d-82f3-df6cd3293f87.jpg)

**Comment by ollerjoaco** [comment]
As a temporary solution, this will be fixed with setting water default fog to 0, this will also avoid players not seeing well underwater and having an advantage being underwater as they can see up but the ones up cannot see the players under the water if they are far.
