### ISSUE TITLE
Not all water on the maps is supported by Trinity

### ISSUE THREAD

**Issue by Nord1cWarr1or** [ollerjoaco/MH_TrinityRender#6]
What does water support depend on? On the texture of the water?
The most obvious example: the water on the map cs_mansion. It doesn't turn into water with reflections.

![20230430101120_1](https://user-images.githubusercontent.com/47604048/236510434-dc79503e-be01-4175-a094-10676c10a455.jpg)

![20230430100942_1](https://user-images.githubusercontent.com/47604048/236510456-c912b579-97bc-411d-a6cf-2934b442c4a2.jpg)

**Comment by ollerjoaco** [comment]
This is because those are brushes with a water texture and they are not declared as func_water entities, that´s why Trinity isnt finding the water to render. That map its really old maybe they didnt have func_water at the moment Idk .

**Comment by Nord1cWarr1or** [comment]
> This is because those are brushes with a water texture and they are not declared as func_water entities, that´s why Trinity isnt finding the water to render. That map its really old maybe they didnt have func_water at the moment Idk .

Hm, Okay, I understand.
